name: Deploy Shikala to Server Iraq

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd /var/www
            if [ -d "vite-app" ]; then
              cd vite-app
              git reset --hard
              git pull origin main
            else
              git clone https://github.com/moeendehqan/mobilemarket.git vite-app
              cd vite-app
            fi
            npm install --legacy-peer-deps
            npm run build
          EOF
